### ISSUE TITLE
Training GMN with triplet mode meets error

### ISSUE THREAD

**Issue by island255** [Cisco-Talos/binary_function_similarity#13]
Hi, I am trying to replicate the training of GMN using the triplet mode, but it meets the following errors:

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [200,40] vs. [200,20]
         [[{{node auc/LogicalAnd_1}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/gnn.py", line 219, in <module>
    main()
  File "/code/gnn.py", line 205, in main
    model_train(config, restore=args.restore)
  File "/code/gnn.py", line 98, in model_train
    gnn_model.model_train(restore)
  File "/code/core/gnn_model.py", line 220, in model_train
    self._run_evaluation(validation_set)
  File "/code/core/gnn_model.py", line 174, in _run_evaluation
    batch_generator)
  File "/code/core/model_evaluation.py", line 132, in evaluate
    feed_dict=feed_dict)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [200,40] vs. [200,20]
         [[node auc/LogicalAnd_1 (defined at code/core/model_evaluation.py:102) ]]

Original stack trace for 'auc/LogicalAnd_1':
  File "code/gnn.py", line 219, in <module>
    main()
  File "code/gnn.py", line 205, in main
    model_train(config, restore=args.restore)
  File "code/gnn.py", line 98, in model_train
    gnn_model.model_train(restore)
  File "code/core/gnn_model.py", line 199, in model_train
    self._model_initialize(training_set)
  File "code/core/gnn_model.py", line 139, in _model_initialize
    self._create_network(batch_generator)
  File "code/core/gnn_model.py", line 120, in _create_network
    self._config, node_feature_dim, edge_feature_dim)
  File "code/core/build_model.py", line 228, in build_model
    pair_auc = auc(similarity, placeholders['labels'])
  File "code/core/model_evaluation.py", line 102, in auc
    _, value = tf.compat.v1.metrics.auc(labels, scores, **auc_args)
  File "usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/metrics_impl.py", line 743, in auc
    labels, predictions, thresholds, weights)
  File "usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/metrics_impl.py", line 590, in _confusion_matrix_at_thresholds
    math_ops.logical_and(label_is_pos, pred_is_neg), dtypes.float32)
  File "usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 5672, in logical_and
    "LogicalAnd", x=x, y=y, name=name)
  File "usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "usr/local/lib/python3.7/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()
```
Do you have any ideas to correct it?

**Comment by jimmy-sonny** [comment]
Hi [island255](https://github.com/island255), 
thank you for reporting this bug. I confirm that there is an error when the model is trained in triplet mode.

In order to replicate our results, please use the `pair` mode: this is what we have used in the experiments for the paper.

**Comment by rbsaul** [comment]
I resolved this error by uncommenting line 98 and commenting out line 102 in `model_evaluation.py` (full path: binary_function_similarity/Models/GGSNN-GMN/NeuralNetwork/core/model_evaluation.py).

This replaces `tf.compat.v1.metrics.auc`, which is deprecated, with `tf.metrics.auc`.

**Comment by jimmy-sonny** [comment]
Hi @island255,

I've pushed a fix for this bug: it's related to the different batch size for training and validation in pair and triplet mode.
