### ISSUE TITLE
GGSNN-GMN test on Dataset-2, Dataset-Vulnerabilty?

### ISSUE THREAD

**Issue by wideglide** [Cisco-Talos/binary_function_similarity#14]
Is it possible to run the GGSNN-GMN model on Dataset-2 ( or others) in test mode?  Specifically, is it designed to run on a dataset it was not trained on?

The `config.py` seems to be missing the `['training']['df_train_path']` keys, which are required to initialize the model here:

https://github.com/Cisco-Talos/binary_function_similarity/blob/84af8dd2775ff80ae4385cccb00d99dab5780d35/Models/GGSNN-GMN/NeuralNetwork/core/gnn_model.py#L300-L303

error log

```python
22:24:56 INFO:: Running model testing
Traceback (most recent call last):
  File "/code/gnn.py", line 219, in <module>
    main()
  File "/code/gnn.py", line 213, in main
    model_test(config)
  File "/code/gnn.py", line 122, in model_test
    gnn_model.model_test()
  File "/code/core/gnn_model.py", line 302, in model_test
    build_train_validation_generators(self._config)
  File "/code/core/build_dataset.py", line 55, in build_train_validation_generators
    func_path=config['training']['df_train_path'],
KeyError: 'df_train_path'
```

**Comment by wideglide** [comment]
I'm not sure that this is related, I initialized the model using Dataset-1, which I think just retrieves the `node_feature_dim` and `edge_feature_dim` from the first pair in order to build the model.

Have you seen an error like this before?

<details>
  <summary>error log:</summary>

```python
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/usr/lib/python3/dist-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/lib/python3/dist-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: data.shape = [414,128] does not start with segment_ids.shape = [28]
         [[{{node graph-embedding-net_1/graph-aggregator/UnsortedSegmentSum}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/gnn.py", line 219, in <module>
    main()
  File "/code/gnn.py", line 213, in main
    model_test(config)
  File "/code/gnn.py", line 122, in model_test
    gnn_model.model_test()
  File "/code/core/gnn_model.py", line 326, in model_test
    batch_generator)
  File "/code/core/model_evaluation.py", line 190, in evaluate_sim
    feed_dict=feed_dict)
  File "/usr/lib/python3/dist-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/usr/lib/python3/dist-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/lib/python3/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/usr/lib/python3/dist-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: data.shape = [414,128] does not start with segment_ids.shape = [28]
         [[node graph-embedding-net_1/graph-aggregator/UnsortedSegmentSum (defined at code/core/graph_aggregator.py:107) ]]

Errors may have originated from an input operation.
Input Source operations connected to node graph-embedding-net_1/graph-aggregator/UnsortedSegmentSum:
 Placeholder_4 (defined at code/core/build_model.py:123)
 graph-embedding-net_1/graph-aggregator/mul (defined at code/core/graph_aggregator.py:105)

Original stack trace for 'graph-embedding-net_1/graph-aggregator/UnsortedSegmentSum':
  File "code/gnn.py", line 219, in <module>
    main()
  File "code/gnn.py", line 213, in main
    model_test(config)
  File "code/gnn.py", line 122, in model_test
    gnn_model.model_test()
  File "code/core/gnn_model.py", line 303, in model_test
    self._model_initialize(training_set)
  File "code/core/gnn_model.py", line 139, in _model_initialize
    self._create_network(batch_generator)
  File "code/core/gnn_model.py", line 120, in _create_network
    self._config, node_feature_dim, edge_feature_dim)
  File "code/core/build_model.py", line 225, in build_model
    eval_pairs = model(**model_inputs)
  File "usr/local/lib/python3.7/dist-packages/sonnet/python/modules/base.py", line 396, in __call__
    return self._call(*args, **kwargs)
  File "usr/local/lib/python3.7/dist-packages/sonnet/python/modules/base.py", line 418, in _call
    outputs, subgraph_name_scope = self._template(*args, **kwargs)
  File "usr/lib/python3/dist-packages/tensorflow/python/ops/template.py", line 384, in __call__
    return self._call_func(args, kwargs)
  File "usr/lib/python3/dist-packages/tensorflow/python/ops/template.py", line 323, in _call_func
    result = self._func(*args, **kwargs)
  File "usr/local/lib/python3.7/dist-packages/sonnet/python/modules/base.py", line 226, in _build_wrapper
    output = self._build(*args, **kwargs)
  File "code/core/graph_embedding_net.py", line 176, in _build
    return self._aggregator(node_states, graph_idx, n_graphs)
  File "usr/local/lib/python3.7/dist-packages/sonnet/python/modules/base.py", line 396, in __call__
    return self._call(*args, **kwargs)
  File "usr/local/lib/python3.7/dist-packages/sonnet/python/modules/base.py", line 418, in _call
    outputs, subgraph_name_scope = self._template(*args, **kwargs)
  File "usr/lib/python3/dist-packages/tensorflow/python/ops/template.py", line 384, in __call__
    return self._call_func(args, kwargs)
  File "usr/lib/python3/dist-packages/tensorflow/python/ops/template.py", line 323, in _call_func
    result = self._func(*args, **kwargs)
  File "usr/local/lib/python3.7/dist-packages/sonnet/python/modules/base.py", line 226, in _build_wrapper
    output = self._build(*args, **kwargs)
  File "code/core/graph_aggregator.py", line 107, in _build
    graph_states = self._aggregation_op(node_states_g, graph_idx, n_graphs)
  File "usr/lib/python3/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 11798, in unsorted_segment_sum
    num_segments=num_segments, name=name)
  File "usr/lib/python3/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "usr/lib/python3/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "usr/lib/python3/dist-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "usr/lib/python3/dist-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()
```

</details>

I can tell its because of a batch of function pairs, but I'm not sure why there's a problem with the shape mismatch.

**Comment by yizhicheng1** [comment]
I would like to ask if you have solved the problem of testing the vulnerability dataset under the GGSNN-GMN model. I also encountered the same problem as you.

**Comment by yizhicheng1** [comment]
> Is it possible to run the GGSNN-GMN model on Dataset-2 ( or others) in test mode? Specifically, is it designed to run on a dataset it was not trained on?
> 
> The `config.py` seems to be missing the `['training']['df_train_path']` keys, which are required to initialize the model here:
> 
> https://github.com/Cisco-Talos/binary_function_similarity/blob/84af8dd2775ff80ae4385cccb00d99dab5780d35/Models/GGSNN-GMN/NeuralNetwork/core/gnn_model.py#L300-L303
> 
> error log
> 
> ```python
> 22:24:56 INFO:: Running model testing
> Traceback (most recent call last):
>   File "/code/gnn.py", line 219, in <module>
>     main()
>   File "/code/gnn.py", line 213, in main
>     model_test(config)
>   File "/code/gnn.py", line 122, in model_test
>     gnn_model.model_test()
>   File "/code/core/gnn_model.py", line 302, in model_test
>     build_train_validation_generators(self._config)
>   File "/code/core/build_dataset.py", line 55, in build_train_validation_generators
>     func_path=config['training']['df_train_path'],
> KeyError: 'df_train_path'
> ```

Have you found a solution to this issue yet? I also encountered the same problem
