### ISSUE TITLE
asm2vec is not reproducable because of gensim

### ISSUE THREAD

**Issue by ivanmilevtues** [Cisco-Talos/binary_function_similarity#34]
Hey all,
I've been trying to setup the project and play around with it. However I cannot run asm2vec because of gensim.
Turns out I cannot run `git clone https://github.com/RaRe-Technologies/gensim/`.
The docker file when built fails with:
```
0.276 Cloning into 'gensim'...
0.452 fatal: could not read Username for 'https://github.com': No such device or address
```
I tried adding my git configs, but it turns out that I am unable to clone the `gensim` repository in general, even outside docker.
```remote: Repository 'RaRe-Technologies/gensim' is disabled.
remote: Please ask the owner to check their account.
fatal: unable to access 'https://github.com/RaRe-Technologies/gensim/': The requested URL returned error: 403```

I was going to open issue at their repository, however this is not possible.

Are other people experiencing this if so is there someone who's managed to workaround this issue?

Thanks in advance!

**Comment by ivanmilevtues** [comment]
Hey,
I've tried running the docker for the Models/GGSNN-GMN Neural Network, however you've not specified which version of python3-setuptools is used explicitly so it fails with the installed version.

I've tried different version suggested from stackoverflow and other places, however they don't work. Can you give exact the version?
Thanks!

Here is the error shown when trying to build the Models/GGSNN-GMN/NeuralNetwork Dockerfile:
```
113.3 Collecting grpcio>=1.8.6 (from tensorflow==1.14.0->-r /code/requirements.txt (line 14))
114.3   Downloading https://files.pythonhosted.org/packages/38/98/ca2cb5a81e0e2f3e3a00ebf91338fd3278ea0673e156a7ff2de30fe17113/grpcio-1.59.0.tar.gz (24.8MB)
119.5     Complete output from command python setup.py egg_info:
119.5     Traceback (most recent call last):
119.5       File "<string>", line 1, in <module>
119.5       File "/tmp/pip-build-xqz45mlm/grpcio/setup.py", line 95, in <module>
119.5         import commands
119.5       File "/tmp/pip-build-xqz45mlm/grpcio/src/python/grpcio/commands.py", line 31, in <module>
119.5         import support
119.5       File "/tmp/pip-build-xqz45mlm/grpcio/src/python/grpcio/support.py", line 21, in <module>
119.5         from setuptools import errors
119.5     ImportError: cannot import name 'errors' from 'setuptools' (/usr/lib/python3/dist-packages/setuptools/__init__.py)
119.5     
119.5     ----------------------------------------
120.0 Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xqz45mlm/grpcio/
```

**Comment by LostBenjamin** [comment]
The docker build error for Models/GGSNN-GMN/NeuralNetwork should be fixed by https://github.com/Cisco-Talos/binary_function_similarity/pull/35.
