### ISSUE TITLE
The Problem in the GGSNN-GMN Model

### ISSUE THREAD

**Issue by liaoluoxing** [Cisco-Talos/binary_function_similarity#40]
Hello, dear author.
I meet some problem in the Part 2 of GGSNN-GMN([binary_function_similarity](https://github.com/Cisco-Talos/binary_function_similarity/tree/9c2967025481c3770428c0614981000783225b2d)/[Models](https://github.com/Cisco-Talos/binary_function_similarity/tree/9c2967025481c3770428c0614981000783225b2d/Models)
/GGSNN-GMN/).

When i run the command "Example: run the validation on Dataset-1 using the [model_checkpoint](https://github.com/Cisco-Talos/binary_function_similarity/blob/9c2967025481c3770428c0614981000783225b2d/Models/GGSNN-GMN/NeuralNetwork/model_checkpoint_GGSNN_pair) that we trained on Dataset-1", there are some errors. The following code is the error message:
```bash
Traceback (most recent call last):
  File "/code/gnn.py", line 219, in <module>
    main()
  File "/code/gnn.py", line 209, in main
    model_validate(config)
  File "/code/gnn.py", line 110, in model_validate
    gnn_model.model_validate()
  File "/code/core/gnn_model.py", line 289, in model_validate
    self._model_initialize(training_set, is_training=False)
  File "/code/core/gnn_model.py", line 144, in _model_initialize
    self._create_network(batch_generator, is_training=is_training)
  File "/code/core/gnn_model.py", line 119, in _create_network
    node_feature_dim = first_batch_graphs.node_features.shape[-1]
AttributeError: 'tuple' object has no attribute 'node_features'
```
I suspect that I did some things wrongly. If you can help me, I would be very appreciate. Thank you a lot.

**Comment by iDTer** [comment]
The same problem.

**Comment by iDTer** [comment]
core/gnn_model.py进行如下修改：


def _create_network(self, batch_generator, is_training):
        """Build the model and set _tensors, _placeholders and _model."""
        # Automatically infer the node and edge features dim.

        _it = None
        if is_training and self._config['training']['mode'] == 'triplet':
            _it = batch_generator.triplets()
        else:
            _it = batch_generator.pairs()

        first_batch_graphs = None
        if is_training and self._config['training']['mode'] == 'pair':
            first_batch_graphs, _ = next(_it)
        else:
            first_batch_graphs = next(_it)

        # Set the feature dimensions
        # node_feature_dim = first_batch_graphs.node_features.shape[-1]
        # edge_feature_dim = first_batch_graphs.edge_features.shape[-1]

        # Set the feature dimensions. 
        if isinstance(first_batch_graphs, GraphData):
            node_feature_dim = first_batch_graphs.node_features.shape[-1]
            edge_feature_dim = first_batch_graphs.edge_features.shape[-1]
        elif isinstance(first_batch_graphs, tuple):
            node_feature_dim = first_batch_graphs[0].node_features.shape[-1]
            edge_feature_dim = first_batch_graphs[0].edge_features.shape[-1]
        else:
            raise TypeError("Unexpected type for first_batch_graphs")
