### ISSUE TITLE
Running Trex giving np.float error

### ISSUE THREAD

**Issue by fan1192** [Cisco-Talos/binary_function_similarity#56]
Hi! I was following the step 2 in the Trex readme file to run the inference script on Dataset-Vulnerability. However, there's a np.float error message:

```
docker run --rm -v $(pwd)/../../DBs/Dataset-Vulnerability/pairs/:/pairs -v $(pwd)/Preprocessing/Dataset-Vulnerability-trex/:/traces -v $(pwd)/NeuralNetwork/:/output -it trex-inference conda run --no-capture-output -n trex python3 trex_inference.py --input-pairs /pairs/pairs_testing_Dataset-Vulnerability.csv --input-traces /traces/trex_traces.json --model-checkpoint-dir checkpoints/similarity/ --data-bin-dir data-bin-sim/similarity/ --output-dir /output/Dataset-Vulnerability-trex
Traceback (most recent call last):
  File "trex_inference.py", line 43, in <module>
    from fairseq.models.trex import TrexModel
  File "/code/trex/fairseq/__init__.py", line 32, in <module>
    import fairseq.criterions  # noqa
  File "/code/trex/fairseq/criterions/__init__.py", line 11, in <module>
    from fairseq.criterions.fairseq_criterion import (  # noqa
  File "/code/trex/fairseq/criterions/fairseq_criterion.py", line 12, in <module>
    from fairseq import metrics, utils
  File "/code/trex/fairseq/utils.py", line 20, in <module>
    from fairseq.modules.multihead_attention import MultiheadAttention
  File "/code/trex/fairseq/modules/__init__.py", line 11, in <module>
    from .character_token_embedder import CharacterTokenEmbedder
  File "/code/trex/fairseq/modules/character_token_embedder.py", line 11, in <module>
    from fairseq.data import Dictionary
  File "/code/trex/fairseq/data/__init__.py", line 24, in <module>
    from .indexed_dataset import (
  File "/code/trex/fairseq/data/indexed_dataset.py", line 112, in <module>
    6: np.float,
  File "/opt/conda/envs/trex/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
ERROR conda.cli.main_run:execute(124): `conda run python3 trex_inference.py --input-pairs /pairs/pairs_testing_Dataset-Vulnerability.csv --input-traces /traces/trex_traces.json --model-checkpoint-dir checkpoints/similarity/ --data-bin-dir data-bin-sim/similarity/ --output-dir /output/Dataset-Vulnerability-trex` failed. (See above for error)
```

**Comment by jimmy-sonny** [comment]
Hi @fan1192, thank you for opening this issue.

I've updated the Trex Dockerfile to include the correct numpy library version.
