### ISSUE TITLE
Problem running Trex

### ISSUE THREAD

**Issue by fan1192** [Cisco-Talos/binary_function_similarity#63]
Hi!

I was able to run Trex a few months ago. However, when I tried to run it recently, it was giving an error about omegaconf. 

I tried to adjust the version of omegaconf but didn't find a version that works.

I'm suspecting that it's caused by some sort of version mismatch. 

```
Traceback (most recent call last):
  File "trex_inference.py", line 43, in <module>
    from fairseq.models.trex import TrexModel
  File "/code/trex/fairseq/__init__.py", line 20, in <module>
    from fairseq.distributed import utils as distributed_utils
  File "/code/trex/fairseq/distributed/__init__.py", line 7, in <module>
    from .fully_sharded_data_parallel import fsdp_enable_wrap, fsdp_wrap, FullyShardedDataParallel
  File "/code/trex/fairseq/distributed/fully_sharded_data_parallel.py", line 11, in <module>
    from fairseq.dataclass.configs import DistributedTrainingConfig
  File "/code/trex/fairseq/dataclass/__init__.py", line 6, in <module>
    from .configs import FairseqDataclass
  File "/code/trex/fairseq/dataclass/configs.py", line 23, in <module>
    from omegaconf import II, MISSING
ImportError: cannot import name 'II' from 'omegaconf' (/opt/conda/envs/trex/lib/python3.8/site-packages/omegaconf/__init__.py)
```

**Comment by fan1192** [comment]
It seems that the problem can be solved by add this line to the dockerfile:
`RUN pip install hydra-core==1.1.0 `
